### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by zachMelody** [Zamiell/isaac-save-viewer#1]
The viewer shows wrong achievement. **No.19** is locked but the viewer still show it.
![2022-02-05_153734](https://user-images.githubusercontent.com/20788703/152633210-6bccebfc-81f5-484d-86e0-63d2ab47e16a.jpg)
![2022-02-05_153744](https://user-images.githubusercontent.com/20788703/152633211-a672d98b-df12-40b2-b442-5bc0fddc3d9d.jpg)

**Comment by Zamiell** [comment]
give me your save file

**Comment by zachMelody** [comment]
> give me your save file
[20220205.rep_persistentgamedata1.zip](https://github.com/Zamiell/isaac-save-viewer/files/8007762/20220205.rep_persistentgamedata1.zip)

**Comment by Zamiell** [comment]
the viewer shows achievements that you dont have yet
